CREATE TABLE IF NOT EXISTS public.notification (
  notificationid SERIAL PRIMARY KEY,
  userid INT NOT NULL REFERENCES public.users(userid) ON DELETE CASCADE,
  message VARCHAR(500) NOT NULL,
  createdat TIMESTAMP NOT NULL DEFAULT NOW(),
  isread BOOLEAN NOT NULL DEFAULT FALSE
);

ALTER TABLE public.event
  ADD COLUMN IF NOT EXISTS createdat TIMESTAMP NOT NULL DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS updatedat TIMESTAMP NULL,
  ADD COLUMN IF NOT EXISTS updatedby INT NULL;

ALTER TABLE public.competition
  ADD COLUMN IF NOT EXISTS createdat TIMESTAMP NOT NULL DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS updatedat TIMESTAMP NULL,
  ADD COLUMN IF NOT EXISTS updatedby INT NULL;

ALTER TABLE public.registration
  ADD COLUMN IF NOT EXISTS updatedat TIMESTAMP NULL,
  ADD COLUMN IF NOT EXISTS updatedby INT NULL;

ALTER TABLE public.payment
  ADD COLUMN IF NOT EXISTS updatedat TIMESTAMP NULL,
  ADD COLUMN IF NOT EXISTS updatedby INT NULL;

ALTER TABLE public.ticket
  ADD COLUMN IF NOT EXISTS updatedat TIMESTAMP NULL,
  ADD COLUMN IF NOT EXISTS updatedby INT NULL;
